[package]
name = "AOC_2025"
version = "0.1.0"
edition = "2024"

[lib]
name = "aoc"
path = "lib.rs"

[[bin]]
name = "day_01"
path = "day_01.rs"

[[bin]]
name = "day_02"
path = "day_02.rs"

[dependencies]
